site_name: McGill NLP Project Documentation
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  logo: assets/logo-inverse.png
  favicon: assets/favicon.png
  features:
    - header.autohide

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/McGill_NLP
    - icon: fontawesome/brands/github
      link: https://github.com/mcGill-NLP/wiki
  homepage: https://mcgill-nlp.github.io

copyright: Copyright &copy; 2022 McGill NLP

extra_css:
  - stylesheets/extra.css